const mongoose = require('mongoose');

const ProposalSchema = new mongoose.Schema({
  rfpId: { type: mongoose.Schema.Types.ObjectId, ref: 'Rfp' },
  vendorId: { type: mongoose.Schema.Types.ObjectId, ref: 'Vendor' },
  totalAmount: Number,
  status: { type: String, default: 'Pending' },
  aiScore: { type: Number, default: 0 }, // Score generated by AI
  aiAnalysis: { type: String } // Text analysis
});

module.exports = mongoose.model('Proposal', ProposalSchema);